export { Login } from './Login'
export { Home } from './Home'
export { Register } from './Register'
export { Hotel } from './Hotel'
export { Search } from './Search'
export { Booking } from './Booking'